kaltura/playkit-js-ima

karma.conf.js, test/src/ima.api.spec.js, test/src/ima.spec.js
Please add a detailed description of the change, weather it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.
=> chore: set default mocha timeout to 30000

src/ima.js
Please add a detailed description of the change, weather it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.
=> fix: start ads manager on player ready

src/ima.js
get player data from own config using https://github.com/kaltura/kaltura-player-js/pull/30
=> chore: get player data from own config

test/src/helpers.js
Build is currently failing due to [this](https://github.com/kaltura/playkit-js/commit/336f4ab2b9f1bea95872ec3ece6416a4b33bc530) change in playkit-js.
=> fix(tests): fix tests after loadPlayer API changed

src/ima-state-machine.js
Handle play/pause on ad clicked base on the ima plugin state.
=> fix(FEC-7293): toggle playback on ad clicked

src/ima-state-machine.js, src/ima.js
If change media has been done with empy ad tag url move the plugin to DONE state.
=> fix(FEC-7343): change media from entry with ad to entry without ad is not working

src/ima.js
=> fix: code cleanups

src/ad-type.js, src/ima-state-machine.js, test/src/ima.api.spec.js, test/src/ima.spec.js
Send on AD_LOADED the adType payload.
=> feat: ad type

README.md, docs/configuration.md, src/ima-middleware.js, src/ima.js, test/src/ima-middleware.spec.js
kaios device issues fixes.
Play ad on the same video element but don't preload the media.
=> fix: kaios issues

src/ima.js, test/src/ima.spec.js
Fix conditional check for IMA AdsRenderingSettings object.
=> fix(FEC-8097): adsRenderingSettings aren’t applied

src/ima.js
Before any ad has been started the ads container should be hidden.l
=> fix(FEC-8013): hide ads container on start

webpack.config.js
align with the new bundles mechanism
=> feat: serve ima as external bundle

src/ima.js
=> fix(FEC-8504): null exception

package.json, src/ima.js, test/src/ima.spec.js, yarn.lock
Prepare the plugin before media is loaded using the ```loadMedia```lifecycle hook.
=> feat(FEC-8763): add loadMedia life cycle hook

docs/api.md, flow-typed/types/ima-config.js, src/ima.js
added `locale` in the ima configuration. 
setting this calls the `setLocale` API in the imasdk.
=> feat(FEC-8853): localizing ima interface via config 

src/ima-state-machine.js
add ad data on ad error event if available.
=> feat(FEC-8856): add ad data on ad error event

flow-typed/types/ima-config.js
=> chore: add locale to jsdocs

src/ima-state-machine.js, src/ima.js
Do not show non-linear ad until the `FIRST_PLAY` event
=> fix(FEC-8952): non-linear ad is playing on-top of the bumper

test/src/ima.spec.js
Please add a detailed description of the change, weather it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.
=> chore: skip tests

src/ima.js
Add inBrowserFullscreen in _maybeForceExitFullScreen to check this situation and plays in inline
=> fix(FEC-8996): [iOS] - player exits from in browser full screen on ad

src/assets/style.css, src/ima.js
fix ads will cover only the player
=> fix(FEC-8933): fix ads covered entire page

src/assets/style.css, src/ima.js
Unset height and width for overlay for inline container
=> fix(FEC-9027): overlay ad not displayed

src/ima.js
=> fix(FEC-9112): start time skips the midroll despite the config

docs/api.md, flow-typed/types/ima-config.js, src/ima.js
Exposed the `vastLoadTimeout` value, and set a default of `5000ms` to it.
=> feat(FEC-9074): expose the vastLoadTimeout value

src/ima-engine-decorator.js, src/ima-state-machine.js, src/ima.js
Add fallback for unsupported ads on LG.
IMA doesn’t return the src for unsupported ads on LG TV.
=> fix(FEC-9173): playback failed for unsupported ads.

src/ima-ads-controller.js
`ImaAdsController` exposes `name`. 
See https://github.com/kaltura/playkit-js/pull/368
=> fix(FEC-9192): post bumper doesn't play

package.json, src/ima-engine-decorator.js, src/ima-state-machine.js, src/ima.js, yarn.lock
update `ImaEngineDecorator` according to https://github.com/kaltura/playkit-js/pull/369
=> feat(FEC-9145): support non sibling video tags

docs/api.md, flow-typed/types/ima-config.js, src/ima-engine-decorator.js, src/ima-state-machine.js, src/ima.js
add configuration for playing ads with MSE for IMA different behavior.
=> feat(FEC-9227): support reInit of MSE

package.json, src/ima.js, yarn.lock
add protocol for plugin for Samsung Smart TV bug
=> fix(FEC-9237): add app protocol for ima plugin

docs/api.md, flow-typed/types/ima-config.js, src/ima.js
Expose config for num of redirects in IMA:
`plugins.ima.setNumRedirects`
=> feat(FEC-9279): expose config for num of redirects in IMA

src/ima-state-machine.js, src/ima.js
remove non relevant code after adding engine decorator
=> fix: non relevant code after engine decorator

samples/companion-ads-automatic.html, samples/companion-ads-manual.html, samples/play-ad-now.html, samples/single-inline-linear.html, samples/single-non-linear-inline.html, samples/single-redirect-broken(fallback).html, samples/single-redirect-error.html, samples/single-redirect-linear.html, samples/single-skippable-inline.html, samples/single-vpaid-2.0-linear.html, samples/vmap-bumpers-pre-1-mid-3-post-1.html, samples/vmap-post-bumper.html, samples/vmap-post.html, samples/vmap-pre-1-mid-1-post-1.html, samples/vmap-pre-1-mid-5-post-1.html, samples/vmap-pre-bumper.html, samples/vmap-pre-skip-support.html, samples/vmap-pre.html, src/index.html, test/src/helpers.js
replace mp4 test source to our source from live
=> fix: broken mp4 in tests

src/ima.js
change it to support for multiple active cues(length was missed)
=> fix(FEC-9160): disable tacks on mid-roll

src/ima-state-machine.js, src/ima.js
set back positions for text tracks after midroll, the backgroud text tracks that stuck disappear
=> fix(FEC-9160): track keep showing in background and other keeps playing

.babelrc, package.json, src/ima-ads-controller.js, src/ima-state-machine.js, src/ima.js, yarn.lock
* Implement `playAdNow` api 
Depends on https://github.com/kaltura/playkit-js/pull/398
=> feat(FEC-9323): advertising configuration

src/ima.js
add playsinline config to getCapabilities
=> fix(FEC-9313): IOS when configuration autoplay native weird behaviour

src/ima.js
handle `SKIPPED` event like `COMPLETE`
=> fix(FEC-9373): new layout, the player stuck if skip pre-roll ad

src/ima.js
=> fix(FEC-9290): destroy adDisplayContainer on destroy

src/ima.js
* Do not reject the ima load promise in recoverable error 
* add `catch` handling to avoid getting `Uncaught (in promise)` error in the console
(the 'real' handling is in the ima-middleware)
=> fix(FEC-9496): pre-roll ad failed to play on iPhone Safari 13 when VR no loaded

package.json, src/ima.js, yarn.lock
support config ad as xml (vast response)
depends on https://github.com/kaltura/playkit-js/pull/418
=> feat(FEC-9469): ad layout - xml response

test/src/helpers.js, test/src/ima.spec.js
add unit tests for `playAdNow` api
=> chore: ad layout tests

.travis.yml
Please add a detailed description of the change, weather it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.
=> chore: update version in travis for Jenkins ping

src/ima.js, test/src/ima.spec.js
Issue: reset raise the post-roll in the background, since contentComplete signal post-roll.
Solution: remove the managers of IMA and re-create it on loadMedia.
=> fix: reset raise the post-roll on the background.

src/ima.js
isLive - is a function and not a getter
solves FEC-10730
=> fix(FEC-10730): High number of postrolls - add brackets

src/ima.js
move startTime to the sources config so it will take place only on the a specific source.
=> feat(FEC-10686): move startTime config from playback to sources

src/ima-state-machine.js, src/ima.js, test/src/ima.spec.js, yarn.lock
vpaid exposed by ima on AD_LOADED only so store it for AD_STARTED
Depends on 
https://github.com/kaltura/kaltura-player-js/pull/410
https://github.com/kaltura/playkit-js/pull/540
Solves FEC-10970
=> feat(FEC-10970): expose vpaid field on ad object

src/ima-ads-controller.js, src/ima.js, yarn.lock
Registration and accessing of services (previously known as managers) was moved from ui to KP
KP PR - kaltura/kaltura-player-js#477
UI PR - kaltura/playkit-js-ui#630
So changes needed to be updated also in ima
solves FEC-11475
=> feat(FEC-11475): create service manager that allows registration and accessing of services

docs/api.md, src/ima.js
Add setSessionId option to IMA sdk settings
Solves FEC-10990
=> feat:(FEC-10990): Add setSessionId option to IMA sdk settings

src/ima-state-machine.js
expose missing fields to adIOptions object
solves: FEC-11536
related pr:
https://github.com/kaltura/kaltura-player-js/pull/496
https://github.com/kaltura/playkit-js/pull/608
=> fix(FEC-11536):expose missing fields to adInfo object

.travis.yml, src/assets/style.css, src/ima.js
=> fix(FEC-12219): Macros not being populated in VAST tag
