kaltura/playkit-js-ima

src/ima-state-machine.js, src/ima.js
Bug fixes:
* Content video never started on iOS .
* FEC-7076 - [Win10][Player_V3][HLS][IMA] - When playing html5 player there is only audio
* FEC-7075 - [Win10][Player_V3][HLS][IMA] - In audio track the overlay ad is displayed after replay
* FEC-7036 - Player V3:IMA: DFP auto companions is not working (black screen with audio after clicking play)
=> fix(FEC-7076, FEC-7075, FEC-7036): ios, companions and overlay ad issues

src/ima-state-machine.js, src/ima.js
On Android devices the screen is splitted and we need to align to the left the ad video element.
=> fix(FEC-7058): align ad video tag to the left

src/ima-state-machine.js, src/ima.js, test/src/ima.spec.js
Move to preload content player action to be soon as possible (right after user gesture).
=> fix(FEC-7108, FEC-7057): preload content player right after user gesture

src/ima.js
Non Linear inline overly isn't in the correct place when full screen in Safari.
=> fix(FEC-7135):  fullscreen fix for overlay ad on safari

src/ima-state-machine.js, src/ima.js
When custom playback was used, the content playhead tracker was updated when ad is playing (since it was playing on the same video tag) and causes wrong tracking.
=> fix(FEC-7158, FEC-7153): set content playeahd tracker events only when ad is idle

src/ima-state-machine.js, src/ima.js
When custom playback is used (usually on iOS devices) and postroll is done, we need to set the content src on the video tag (seems like the ima sdk doesn't do it for us).
=> fix(FEC-7150, FEC-7120): set content src on custom playback with postroll

src/ima-middleware.js, src/ima.js, test/src/ima-middleware.spec.js, test/src/ima.api.spec.js
Requesting ads before user gesture can cause kind of a race condition - if the tap on play was too early and ad manager was still not loaded, a delay timeout of the loadPromise was caused to an ad error event.
Another important change is to load the player ASAP for avoid errors on mobile (mainly on Android/Chrome)
=> fix(FEC-7166, FEC-7165, FEC-7159, FEC-7119, FEC-7114): manage races on play

src/ima.js, test/src/ima.spec.js
This flag disables iOS's native fullscreen and causing problems if playinsline not set to true.
=> fix(FEC-7184): remove setDisableCustomPlaybackForIOS10Plus flag

src/ima.js, test/src/ima.spec.js
Because of overriding updateConfig we're calling twice to requestAds what causing empty vast response and ad error.
We need to re-think on design and implementation of 2 features:
* Create IMA plugin without ad tag ad configure it later.
* Play ad on demand
=> fix(FEC-7214, FEC-7217, FEC-7214): multiple request ads fix

src/ima-state-machine.js, test/src/helpers.js
If an overlay ad is playing and user clicked on it, pause video.
If the video is already paused and user clicked on it, play video.
=> fix(FEC-7234): pause playback on overlay ad clicked

src/ima.js
Sets ima setting  setDisableCustomPlaybackForIOS10Plus according to the player's playsinline config.
If setDisableCustomPlaybackForIOS10Plus is configured by the user, it is the strongest config.
=> fix(FEC-7199): handling setDisableCustomPlaybackForIOS10Plus

src/ima-state-machine.js, src/ima.js
Listen also for MUTE_CHANGE event from the player to change the adsManager volume, so the flow after user action will be synchronously.
=> fix(FEC-7372, FEC-7369, FEC-7376, FEC-7386): fallback to mute issue

src/assets/style.css, src/ima-state-machine.js, src/ima.js, webpack.config.js
Add ad cover overlay on ad paused, remove it on ad resumed.
=> fix(FEC-7365): when click again on paused ad the ad resumed but click-through site is open again

src/ima-middleware.js, test/src/ima-middleware.spec.js
when ad response is malformed we get a rejection of promise, but because int's a nested promise and we didn't `return` it then the external `catch` didn't get triggered and the code flow got stuck.
=> fix(FEC-7516): fix IMA get stuck when ad response is bad

src/ima.js, test/src/ima.spec.js
resolve the `_nextPromise` immediately if no adTagUrl given, to not block the play middleware chain
=> fix(FEC-7516): player gets stuck when ima plugin is empty

src/ima-state-machine.js
Move the `_setToggleAdsCover ` also if ad clicked when its not playing.
=> fix(FEC-7898): After pausing ad, each time clicking on the Ad area Ad info displayed (and video is not Playing)

src/ima-middleware.js, src/ima-state-machine.js, src/ima.js
Inside the plugin use only IMA's adsManager API and not plugin API which overrides the next promise.
=> fix(FEC-7502, FEC-7455): Video stuck after the ad ,In case user was selecting learn more during ad and select Play (big icon)

src/ima.js
For some reason on mobiles the click on 'Learn More' is catching on the ad cover, so need to check what to do depends on the plugin state.
=> fix(FEC-7915): When selecting learn more (long press) on pre-roll the ad page is opening and video continues to play

src/ima-state-machine.js, src/ima.js
Ignoring LearnMore click to enable video element manipulation only on user gesture.
=> fix(FEC-7403): [DFP_Preroll][Android] - When tapping on learn more on a pre roll, then closing the new opened tab, the video is not playing

src/ima-middleware.js
Following https://github.com/kaltura/playkit-js/pull/197 playing an ad can be before `sourceselected` event, so we have to consider this use case when ima preloads the source
=> fix: wait for source before preloading the entry 

src/ima.js
When ad blocker is active then IMA SDK doesn't load.
We protect against such case for the current playback and avoid accessing IMA SDK, but on change media we don't check this condition again and call the IMA SDK, which doesn't exist, and this crash the player.
=> fix(FEC-8065): protect against accessing IMA SDK when it is not loaded

src/ima.js
Following the new autoplay changes in Chrome and other browsers IMA are making autoplay and muted playback as key attributes in their attribution and ad buying process.
As part of this they are requesting that the following APIs will be set accordingly so this data, if ad will be played autoplay or/and muted, will be passed to the ad server.
Setting of the data is via API:
[setAdWillAutoPlay](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsRequest.setAdWillAutoPlay)
[setAdWillPlayMuted](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsRequest.setAdWillPlayMuted)
See:
https://github.com/googleads/googleads-ima-html5/blob/master/attempt_to_autoplay/ads.js
**Still need to add docs update**
=> feat(FEC-7814): add setAdWillAutoPlay and setAdWillPlayMuted support

src/ima-state-machine.js, src/ima.js
When playing with different video tags on iOS ads are not
supported in native full screen, so need to exist full screen before ads started.
=> fix(FEC-8107):  ad video fails to play and only ad audio plays in full screen mode

src/assets/style.css, src/ima-state-machine.js, src/ima.js
Also fixes issue when tap on Ad and return to player, the playback doesn't resumed on iPhone.
=> fix(FEC-8111, FEC-8022): set ads container dimensions according to the ad width/height

src/ima.js
=> fix(FEC-8129): playback starts while ad is playing if only adsResponse is configured

src/ima-state-machine.js
Change the plugin state to IDLE only when ad break end.
=> fix(FEC-8092): playback start while ad is playing when calling play on ad completed

karma.conf.js, src/ima-state-machine.js, src/ima.js
Add `delayInitUntilSourceSelected` flag which will prevent initialisation of the plugin until source selected.
=> fix(FEC-8131): skippable ads fail on iOS

src/ima-state-machine.js
add ad type data attribute to the ads container
related to https://github.com/kaltura/playkit-js-ui/pull/228
=> fix(FEC-8142): overlay ad clickthrough doesn't work

src/ima-state-machine.js
No need to destroy the plugin when ALL_ADS_COMPLETED is triggered.
Most of the destroy actions are already done on:
AD_COMPLETED
AD_BREAK_END
which been called before ALL_ADS_COMPLETED.
The destroy do in addition eventManager.destroy which remove all listeners and when we are unmuting the media we are not updating the ads manager's volume.
=> fix(FEC-7406): preroll doesn't played on change media while unmute the previous media

src/ima.js
If the plugin has been destroyed while calling the promise in reset the adsLoader will no longer exists so we need to add protection.
=> fix(FEC-8239): IMA exception when calling reset followed by destroy

src/ima.js, test/src/ima.spec.js
fix(FEC-8352): DRM and IMA on http, the ad is playing but after the ad there is a black screen
Reset ima plugin on a critical error
=> feat(FEC-8295): Show error UI on network error while playing ads

.flowconfig, flow-typed/modules/playkit-js.js, package.json, src/ima-middleware.js, src/ima-state-machine.js, src/ima.js, src/index.js, test/src/helpers.js, test/src/ima.api.spec.js, test/src/ima.spec.js, test/src/utils/test-utils.js, webpack.config.js, yarn.lock
IMA plugin loads next ad on reset, but reset can also be called when app just wants to stop current playback but not change media to next one.
fixes FEC-8517
=>  fix(FEC-8517): don't preload ad on reset

src/ima.js
If ad load fails on a media and then change media is preformed then it will get stuck because the adsLoader was destroyed and it will never be re initialized again.
=> fix(FEC-8762): subsequent media change after ad load fail are stuck

src/ima-middleware.js, src/ima-state-machine.js, src/ima.js, test/src/ima-middleware.spec.js
in addition to #82 this PR will handle wrongful event manager destroying and in general will prevent calling the destroy from within the plugin cause this means that plugin should not be used anymore, while we only want to reset it until next media will be played.
=> fix(FEC-8762): destroy is called incorrectly in plugin life cycle

src/ima.js, test/src/ima.spec.js
1. Added the 'vpaidmode' const which will check if the selected VPAID mode config is defined correctly, and will pass it as a number.
Logged the selected VPAID mode to the console.
2. Will default to 'ENABLED' when VPAID mode is not set, or written incorrectly.
Warn the user that VPAID is defaulting to 'ENABLED'
=> fix(FEC-8740): VPAID is still defaulting to ENABLED

package.json, src/ima-state-machine.js, test/src/ima.spec.js, yarn.lock
* calculate the ad data according the ad type
* send the ad as a payload of `AD_STARTED` event - when the ad data exists.
Depends on https://github.com/kaltura/playkit-js/pull/334
=> feat(FEC-8749): expose IMA ad data

src/ima.js, test/src/ima.spec.js
set `playAdsAfterTime` according the `playback.startTime` config
=> feat(FEC-8751): add support for ima playAdsAfterTime setting

src/ima.js
Added ima' default timeout to the rendering configuration (-1 = 8 seconds)
The application can configure otherwise:
```
adsRenderingSettings: {
loadVideoTimeout: 20
}
```
=> feat(FEC-8815): support vast timeout

src/ima-state-machine.js
`this._currentAd` was `null`,
getting the `duration` from `adEvent.getAdData()`
=> fix(FEC-8891): a bumper after an ad cannot be clicked

src/ima.js
listen to the player resize event instead of the window's
=> fix(FEC-8844): listen to the player resize event instead of the window's

src/ima-state-machine.js
Relocated `currentAd` from from `onAdCompleted` to `onAdBreakEnd` in order to resolve the issue when ads are getting called complete when the adTag is still present.
=> fix(FEC-8936): VPAID ads may cause player crash

src/ima.js
force delay until video tag will be loaded and then load the ima, ima ads take the inline configure from our video tag
=> fix(FEC-9013): [iOS] - Player doesnt play ads native when playsinline is false

package.json, yarn.lock
get state machine from kaltura, add patch for browser implementation error of shift function in LG TV browser.
=> fix(FEC-9058): get state machine from kaltura with patch for LG TV

src/ima-state-machine.js
add `system` to the ad event payload
Depends on https://github.com/kaltura/playkit-js/pull/362
=> fix: ad system is missing in the ad event payload

package.json, yarn.lock
get state machine from kaltura, add patch for browser implementation error of shift function in LG TV browser. add tag to javascript-state-machine and change it on package.json
=> fix(FEC-9058): get state machine from kaltura with patch

package.json, yarn.lock
get state machine from kaltura, add patch for browser implementation error of shift function in LG TV browser. add tag to javascript-state-machine and change it on package.json
=> fix(FEC-9058): incorrect package dependency(javascript-state-machine)

src/ima.js
Issue: loadmetadata event doesnt get dispatched, which cause invisible seekbar.
solution: exclude loaded state from `isAdPlayingOnSameVideoTag` method - if ads didn't start or load yet then allow player events to be dispatched.
=> fix(FEC-9111): seekbar doesn't work on WebOS

src/ima.js
Add default protocol https when our bundled application loaded with non valid protocol(not http or https).
Found on Samsung TV.
=> fix(FEC-9167): set default IMA lib protocol for non http protocols

CHANGELOG.md, karma.conf.js, package.json, src/ima-ads-controller.js, src/ima-state-machine.js, src/ima.js, test/src/ima.spec.js, yarn.lock
* `IAdsPluginController` implementing (`active`, `done` getters)
* change `ALL_ADS_COMPLETED` to `ADS_COMPLETED` (for multiple ads plugins support)
* add `bumper` flag on ad
* do not show non-linear ad during bumper
* Wait for `AdsController` triggering to play the postroll 
Dependes on https://github.com/kaltura/playkit-js/pull/350
=> feat(FEC-8631): bumper plugin

src/ima-engine-decorator.js, src/ima-state-machine.js, src/ima.js
Playback will keep playing for hls.js and native when unsupported ads are playing on same video tag.
=> fix(FEC-9173): playback failed for unsupported ads.

src/ima.js
move ima state machine to `DONE` when no `adTagUrl/adsResponse` configured
=> fix(FEC-9209): when bumper and ima plugins enabled in player, no big replay button at the end

src/ima-state-machine.js, src/ima.js
* restore the playback source when ad break ended but only is the source exists  
* restore the selected tracks and rate when switching back to the playback
=> fix(FEC-9273): playing preroll on AV player (ios+playsinline=false) gets the player stuck

src/ima-state-machine.js, src/ima.js
change position of activeCue remove the text tracks from ui
=> fix(FEC-9160): captions displayed during midroll ad on AVplayer

src/ima.js
ACT: IMA getVolume method response the same volume as was in player and we won't change the volume.
SOLUTION: always change the volume in IMA when player volume was changed
=> fix(FEC-9367): unmate button doesn't change the ad volume

src/ima.js
* Do not dispatch `ALL_ADS_COMPLETED` on error before the `FIRST_PLAY`
=> fix(FEC-9429): new ad layout - stopped source will autoplay if AD_ERROR occurs on preroll URL

src/ima-state-machine.js, src/ima.js
* **Issue:** no user gesture 
**Solution:** use the new `USER_GESTURE` event to initialize the ad video element (unless the ad video already played so it's unnecessary)
* Keep on `PENDING` when `AD_VOLUME_CHANGED` occuer while pending
Depends on https://github.com/kaltura/playkit-js/pull/415
Solves [FEC-9483](https://kaltura.atlassian.net/browse/FEC-9483)
=> fix(FEC-9483): ad layout - no mid-roll ads play on iPad

package.json, src/ima-state-machine.js, src/ima.js, yarn.lock
consider `ad.bumper` config
depends on https://github.com/kaltura/playkit-js/pull/420
=> feat(FEC-9470): ad layout - bumper support

package.json, src/ima-middleware.js, test/src/ima.spec.js, yarn.lock
* Since https://github.com/kaltura/playkit-js/pull/431 need to load the next also when:
`disableMediaPreload: true` ,`playOnMainVideoTag :true`
once the pre-roll finished or failed 
* update playkit to `0.59.2`
Solves FEC-9594
=> fix(FEC-9594): the playback failed after the pre-roll finished when "disableMediaPreload: true"

src/ima.js
This reverts commit 37af209e as is unneeded any more due to https://github.com/kaltura/kaltura-player-js/pull/302
Solves FEC-9629
=> fix(FEC-9629): Player is not inline when rendered after the DOM loads

src/ima.js
If trying to resize the ad in ima to a smaller size then an error is thrown from IMA.
Therefore we check in the resize wether the player dimensions is enough to show the ad if not we hide it.
solves FEC-10251
=> fix(FEC-10251): floating player - no linear Ad isn't resized when moved to floating player

src/ima-state-machine.js, src/ima.js
IMA probably changed their adloaded timing which causes issues on our logic with text tracks.
Issue: text tracks hide 5-6 sec before ad start, adloaded called 5-6 sec before which make this issue.
Solution: relocate the logic for text tracks to adbreakstart.
Solve FEC-10335.
=> fix(FEC-10335): text tracks doesn't show correctly on IOS same video tag

docs/api.md, docs/cue-points.md, docs/guides.md, flow-typed/types/ima-config.js, package.json, src/ima.js, yarn.lock
use the new `addCuePoint` for the ad breaks when configured 
Depends on https://github.com/kaltura/playkit-js-timeline/pull/1
=> feat(FEC-10015): support smart scrubber preview and timeline marker

src/ima.js
Because IMA doesn't know the video duration the post roll is loaded long before it is supposed to be played.
Solution suggested by google IMA is to send the duration in ad request.
solves FEC-10730
=> fix(FEC-10730): High number of postrolls

src/ima.js
Issue: adsLoader doesn't exist if an error occurs before the end(reset called).
Solution: add protection for adsLoader and call contentComplete only if it exists
=> fix(FEC-10837): unhandled error thrown by ima on playback ended after ad error

src/ima-middleware.js
Issue: load middleware got stuck.
Solution: add a call for the next load on load promise rejection.
=> fix(FEC-10838): disableMediaPreload with ad blocker stuck the player

src/ima.js
Issue: Youbora keeps the `e.payload.adBreakPosition` on `AD_MANIFEST_LOADED`, and changes it on `AD_PROGRESS` for internal use. This causes the ima's `cuePoints` to changed.
Solution: Passing a copy of the `cuePoints` on `AD_MANIFEST_LOADED` to keep it read-only
Solves FEC-10865
=> fix(FEC-10865): postroll is not playing when try to play pre-mid-post

src/ima.js
`window.googletag` now exists despite it's manual companion, so add `window.googletag.cmd` to the condition 
Solves FEC-10983
=> fix(FEC-10983): manual companions does not work

src/ima-state-machine.js
This is basically an IMA issue when the ads manager state is not synced with the AD_PROGRESS event data. On ads switching, when AD_PROGRESS event is raised, the remaining time of the ads manager referring to the new ad but the duration of the ad event referring to the previous ad.
Solution is to check if this calculation produce negative number and in this case set it to 0.
=> fix(FEC-10905): when move from ad to other ad there is a second when wrong time is shows

src/ima.js
The issue is only when the post-roll preloaded, so prevent post-roll preloading 
Solves FEC-11059
=> fix(FEC-11059): no replay button once ima postroll failed when midroll has skipped over

docs/api.md, docs/cue-points.md, src/ima-middleware.js
Fact: when `AD_ERROR` is raised and the ad is not the last in the pod, the next load function in the chain is called, which will activate the player's engine load.
Problem: when ima-dai decorator exists, this will cause to skip its load. Then, on play, when the decorator is active, none of its variables were initialised.
Solution: check that the ad is the last ad in the pod to allow calling the next load function.
=> fix(FEC-11198): Player showing "NaN" values for duration

karma.conf.js, package.json, src/ima.js, test/setup/linear-image.vast.xml, test/src/ima.spec.js, yarn.lock
In linear image (fullslot) ads, the SDK sends STARTED event before CONTENT_PAUSE_REQUESED, causing us to fire AD_STARTED before AD_BREAK_STARTED and breaking the ad ui. 
In case the event order is reversed, AD_STARTED will not fire until CONTENT_PAUSE_REQUESTED is recieved.
Fixes FEC-10583.
Related PR: https://github.com/kaltura/playkit-js-ui/pull/634
=> fix(FEC-10583): fix linear image ads

src/ima-state-machine.js, src/ima.js
When user clicks through a linear ad, only pause it if it's a video ad
Fixes FEC-10583
=> fix(FEC-10583): IMA image ad is not functional

src/ima-state-machine.js
**issue:**  ima launched the new “pause” behavior since April 16, 2021 look at  https://ads-developers.googleblog.com/2020/09/changes-to-pause-behavior-in.html 
**fix:**  resume the ad manually on live
solves: FEC-11757
=> fix(FEC-11757): V3: live with Ad: UI wrong state (Video is paused) after closing the new opened Ad tab

.flowconfig, src/ima.js, test/src/ima.spec.js
`window.googletag.cmd` exists also when it's manually companions but as an empty array so check if it's not an object 
Solves FEC-10983
=> fix(FEC-10983): Manual companions do not work

src/ima-middleware.js, test/src/ima.spec.js
call to next load if it's non-linear ad
Solves FEC-12019
=> fix(FEC-12019): samsung - non linear ad - video does not start after clicking Play

src/ima-state-machine.js, src/ima.js, test/src/ima.spec.js
for vpaid keep the playkit-ads element dimensions like the player dimensions since ima calculates the vpaid position based on it. 
this change causes the player overlay to be unclickable when non-linear vpaid is displayed.
only the center playback controls get z-index to let the user pause/play the player during the non-linear vpaid is displayed on small screen - see https://github.com/kaltura/playkit-js-ui/pull/677
also, add missing states for non-linear vpaid
Solves FEC-12236, FEC-12237
=> fix(FEC-12236,FEC-FEC-12237): VPAID ads part of the AD is cut

src/ima.js
On smart tv, the currentTime was being taken from the engine decorator instead of from the video element, and it was always zero, so we never saved the actual time before starting the mid-roll ad. Taking the time from the video element fixes the issue.
Resolves FEC-12067
=> fix(FEC-12067): [TV Samsung] - Video restart from beginning after Mid-Roll
